// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARz2fKlCr8ulOau1qKezgv2srYANbTA-s',
    appId: '1:944091414024:web:38d1ae49267d6031c79bbd',
    messagingSenderId: '944091414024',
    projectId: 'mobile-transfert-app',
    authDomain: 'mobile-transfert-app.firebaseapp.com',
    storageBucket: 'mobile-transfert-app.appspot.com',
    measurementId: 'G-JPNZFD57LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0MZNgvg1hUFLF_fe6whhJz3B0KByAEvc',
    appId: '1:944091414024:android:6beccf994e2c4a13c79bbd',
    messagingSenderId: '944091414024',
    projectId: 'mobile-transfert-app',
    storageBucket: 'mobile-transfert-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMi4Y28MImDKFQfId2DdW-Rqh2UdRo1iw',
    appId: '1:944091414024:ios:ce6a67046ba7b8d5c79bbd',
    messagingSenderId: '944091414024',
    projectId: 'mobile-transfert-app',
    storageBucket: 'mobile-transfert-app.appspot.com',
    iosBundleId: 'com.example.mobileTransfertApp',
  );
}
